# -*- coding: utf-8 -*-
"""Tuplas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s20VVd99m7reh7WxMbjvP5UzAYV8yz3A
"""

# EXERCÍCIO 1

f = ('maça','pera','uva','laranja','pera')
p_elemento = f [2]

print(p_elemento)

# EXERCÍCIO 2

nuns = (1, 23, 21 , 32 , 12 , 4 , 6 , 75 ,9)
lista = list(nuns)

print(lista)

# EXERCÍCIO 3

meses = ('janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro')
for x in meses:

    print(x)

# EXERCÍCIO 4

notas = [4.5 , 8.0 , 5.0 , 4.5 , 2.0]
notas2 = tuple(notas)
print(notas2)



# EXERCÍCIO 5

ponto = [10,25]

x,y = ponto

print ('Coordenada X:',x)
print ('Coordernada Y:',y)